export class FXRenderer {
  constructor(canvas, overlay) { this.c=canvas; this.x=canvas.getContext('2d',{alpha:false}); this.o=overlay; this.ox=overlay.getContext('2d'); this.fx=document.createElement('canvas'); this.mask=document.createElement('canvas'); this.invisible=0; }
  resize(w,h){ this.c.width=this.o.width=this.fx.width=this.mask.width=w; this.c.height=this.o.height=this.fx.height=this.mask.height=h; }
  capture(v){ const c=document.createElement('canvas'); c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return c; }
  reset(){this.invisible=0;}
  point(p,s){return {x:(s.mirror?1-p.x:p.x)*this.c.width,y:p.y*this.c.height};}
  video(ctx,v,s,w=this.c.width,h=this.c.height){ctx.save();if(s.mirror){ctx.translate(w,0);ctx.scale(-1,1);}ctx.drawImage(v,0,0,w,h);ctx.restore();}
  quad(d,s){if(d.hands.length<2)return null;const a=d.hands[0].p,b=d.hands[1].p;return [a[4],a[8],b[8],b[4]].map(p=>this.point(p,s));}
  path(q,x=this.x){x.beginPath();q.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.closePath();}
  render(v,d,s,bg,t,segmentation){const w=this.c.width;if(!w)return;this.video(this.x,v,s);if(['frame','twist','anime'].includes(s.mode))this.frame(v,d,s);if(s.mode==='invisible')this.invisibleFx(s,bg,segmentation,t);this.debug(d,s);}
  frame(v,d,s){const q=this.quad(d,s);if(!q)return;const f=this.fx.getContext('2d',{willReadFrequently:true});f.clearRect(0,0,this.fx.width,this.fx.height);this.video(f,v,s);let img=f.getImageData(0,0,this.fx.width,this.fx.height), a=img.data, level=s.posterize||5, pixel=s.pixelSize||10;
    for(let y=0;y<this.fx.height;y++)for(let x=0;x<this.fx.width;x++){let i=(y*this.fx.width+x)*4,r=a[i],g=a[i+1],b=a[i+2]; if(s.mode==='anime'){let edge=(x&&y)?Math.abs(r-a[i-4])+Math.abs(g-a[i-3])+Math.abs(b-a[i-2]):0;let qv=255/(level-1);a[i]=a[i+1]=a[i+2]=edge>90?10:Math.round((r+g+b)/3/qv)*qv;}else if(s.frameEffect==='pixel'||s.frameEffect==='retro'){let qv=255/(s.colorDepth||5);a[i]=Math.round(r/qv)*qv;a[i+1]=Math.round(g/qv)*qv;a[i+2]=Math.round(b/qv)*qv;}else if(s.frameEffect==='mono'){let z=(r+g+b)/3;a[i]=z;a[i+1]=z;a[i+2]=z;}else if(s.frameEffect==='cmyk'){a[i]=255-r;a[i+1]=255-g;a[i+2]=255-b;}else {a[i]=Math.min(255,r*1.3+35);a[i+1]=Math.min(255,g*.8);a[i+2]=Math.min(255,b*1.4+25);}}
    f.putImageData(img,0,0);if(s.frameEffect==='pixel'||s.frameEffect==='retro'){const small=document.createElement('canvas');small.width=Math.max(1,this.fx.width/pixel);small.height=Math.max(1,this.fx.height/pixel);const sx=small.getContext('2d');sx.drawImage(this.fx,0,0,small.width,small.height);f.imageSmoothingEnabled=false;f.clearRect(0,0,this.fx.width,this.fx.height);f.drawImage(small,0,0,this.fx.width,this.fx.height);}
    this.x.save();this.path(q);this.x.clip();this.x.drawImage(this.fx,0,0);this.x.restore();this.path(q);this.x.strokeStyle=s.borderColor||'#4cfbff';this.x.lineWidth=s.borderWidth||3;this.x.shadowColor=this.x.strokeStyle;this.x.shadowBlur=s.edgeGlow||12;this.x.stroke();this.x.shadowBlur=0;
  }
  invisibleFx(s,bg,seg){const target=s.gesture==='OPEN'?1:0;this.invisible+=(target-this.invisible)*Math.min(1,16/(s.transitionDuration||1000));if(this.invisible<.01||!bg)return;const x=this.x,w=this.c.width,h=this.c.height,m=this.mask.getContext('2d');m.clearRect(0,0,w,h);
    if(seg?.data){const im=m.createImageData(w,h), sw=seg.width,sh=seg.height;for(let y=0;y<h;y++)for(let xx=0;xx<w;xx++){const si=Math.floor(y/h*sh)*sw+Math.floor((s.mirror?1-xx/w:xx/w)*sw);if(seg.data[si]>.45)im.data[(y*w+xx)*4+3]=255;}m.putImageData(im,0,0);}else return;
    const rep=this.fx.getContext('2d');rep.clearRect(0,0,w,h);this.video(rep,bg,s);rep.globalCompositeOperation='destination-in';rep.drawImage(this.mask,0,0);rep.globalCompositeOperation='source-over';x.save();x.globalAlpha=this.invisible;x.drawImage(this.fx,0,0);x.restore();
  }
  debug(d,s){const x=this.ox;x.clearRect(0,0,this.o.width,this.o.height);if(!s.debug)return;x.strokeStyle='#62ffe4';x.fillStyle='#fff';x.lineWidth=2;d.hands.forEach(hand=>{d.bones.forEach(([a,b])=>{x.beginPath();const p=this.point(hand.p[a],s),q=this.point(hand.p[b],s);x.moveTo(p.x,p.y);x.lineTo(q.x,q.y);x.stroke();});hand.p.forEach((p,i)=>{const q=this.point(p,s);x.fillRect(q.x-2,q.y-2,5,5);x.fillText(i,q.x+4,q.y-4);});});}
}
