import { MoswFx } from './moswFx.js';
import { EmojiAssets } from './emojiAssets.js';
import { circleIntersectsPolygon } from './geometry.js';
import { stepHandFlowParticles,stepBodyWindParticles } from './particleFlow.js';

export function drawClippedFrame(context,image,quad){context.save();context.beginPath();quad.forEach((point,index)=>index?context.lineTo(point.x,point.y):context.moveTo(point.x,point.y));context.closePath();context.clip();context.drawImage(image,0,0);context.restore();}
export function handFlowForce(particle,hands,state){
  let ax=0,ay=0;
  for(const hand of hands){const dx=particle.x-hand.screen.x,dy=particle.y-hand.screen.y,distance=Math.max(1,Math.hypot(dx,dy)),radius=state.flowRadius||240,strength=state.flowStrength||1;
    if(hand.gesture==='OPEN'&&distance<radius){const force=(1-distance/radius)*strength*.085;ax+=dx/distance*force;ay+=dy/distance*force;}
    if(hand.gesture==='FIST'){const local=distance<radius?(1-distance/radius)*.12:.012;const slow=Math.max(.18,Math.min(1,distance/(radius*.35)));ax-=dx/distance*strength*local*slow;ay-=dy/distance*strength*local*slow;}
  }
  return {x:ax,y:ay};
}

export class FXRenderer{
  constructor(canvas,overlay){this.c=canvas;this.x=canvas.getContext('2d',{alpha:false});this.o=overlay;this.ox=overlay.getContext('2d');this.fx=document.createElement('canvas');this.mask=document.createElement('canvas');this.particleLayer=document.createElement('canvas');this.mosw=new MoswFx();this.emoji=new EmojiAssets();this.invisible=0;this.particles=[];this.stableQuad=null;this.quadSeen=0;this.lastParticleTime=0;this.lastMode='';this.particleCursor=0;this.particleRespawns={count:0,rate:0,since:0};this.photoFrame=null;this.bodyWind={};}
  resize(w,h){for(const canvas of [this.c,this.o,this.fx,this.mask,this.particleLayer]){canvas.width=w;canvas.height=h;}this.mosw.resize(w,h);this.particles=[];}
  capture(v){const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return c;}
  reset(){this.invisible=0;this.particles=[];this.stableQuad=null;this.photoFrame=null;this.particleLayer.getContext('2d').clearRect(0,0,this.particleLayer.width,this.particleLayer.height);}
  point(p,s){return {x:(s.mirror?1-p.x:p.x)*this.c.width,y:p.y*this.c.height};}
  video(ctx,v,s,w=this.c.width,h=this.c.height){ctx.save();if(s.mirror){ctx.translate(w,0);ctx.scale(-1,1);}ctx.drawImage(v,0,0,w,h);ctx.restore();}
  quad(d,s){if(d.hands.length<2)return null;const a=d.hands[0].p,b=d.hands[1].p;return [a[4],a[8],b[8],b[4]].map(p=>this.point(p,s));}
  path(q,x=this.x){x.beginPath();q.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.closePath();}
  render(v,d,s,bg,t,segmentation,faces=[],pose=null){if(!this.c.width)return;if(this.lastMode&&this.lastMode!==s.mode&&s.mode==='dissolve'){this.particles=[];this.particleLayer.getContext('2d').clearRect(0,0,this.particleLayer.width,this.particleLayer.height);}this.video(this.x,v,s);if(s.mode==='frame'){if(this.photoFrame)this.drawPhotoFrame(faces,pose,d,s,t);else this.frame(v,d,s,t);}else if(s.mode==='anime')this.frame(v,d,s,t);if(s.mode==='anime'&&s.faceEmoji)this.drawFaceEmojis(faces,s,t);if(s.mode==='invisible')this.invisibleFx(s,bg,segmentation,t);if(s.mode==='dissolve')this.dissolve(s,segmentation,d,t,pose);this.debug(d,s,segmentation,faces,pose);this.lastMode=s.mode;}
  updateStableQuad(d,s,now){const detected=this.quad(d,s);if(detected){this.stableQuad=this.stableQuad?detected.map((p,i)=>({x:this.stableQuad[i].x*.68+p.x*.32,y:this.stableQuad[i].y*.68+p.y*.32})):detected;this.quadSeen=now;}return now-this.quadSeen<350?this.stableQuad:null;}
  frame(v,d,s,now=performance.now()){const quad=this.updateStableQuad(d,s,now);if(!quad)return null;const context=this.fx.getContext('2d',{willReadFrequently:true});context.setTransform(1,0,0,1,0,0);context.globalAlpha=1;context.globalCompositeOperation='source-over';context.filter='none';context.clearRect(0,0,this.fx.width,this.fx.height);this.video(context,v,s);const useClassic=s.mode==='anime'||s.frameRenderer !== 'mosw';if(useClassic)this.classicFrame(context,s);const rendered=s.mode==='frame'&&!useClassic?this.mosw.apply(this.fx,s,now,s.beatPhase||0):this.fx;drawClippedFrame(this.x, rendered, quad);this.path(quad);this.x.strokeStyle=s.borderColor||'#4cfbff';this.x.lineWidth=s.borderWidth||3;this.x.shadowColor=this.x.strokeStyle;this.x.shadowBlur=s.edgeGlow||12;this.x.stroke();this.x.shadowBlur=0;return quad;}
  classicFrame(context,s){const image=context.getImageData(0,0,this.fx.width,this.fx.height),data=image.data,level=s.posterize||5,pixel=s.pixelSize||10;for(let y=0;y<this.fx.height;y++)for(let x=0;x<this.fx.width;x++){const i=(y*this.fx.width+x)*4,r=data[i],g=data[i+1],b=data[i+2];if(s.mode==='anime'){const edge=x&&y?Math.abs(r-data[i-4])+Math.abs(g-data[i-3])+Math.abs(b-data[i-2]):0,step=255/(level-1);data[i]=data[i+1]=data[i+2]=edge>90?10:Math.round((r+g+b)/3/step)*step;}else if(['pixel','retro'].includes(s.frameEffect)){const step=255/(s.colorDepth||5);data[i]=Math.round(r/step)*step;data[i+1]=Math.round(g/step)*step;data[i+2]=Math.round(b/step)*step;}else if(s.frameEffect==='mono')data[i]=data[i+1]=data[i+2]=(r+g+b)/3;else if(s.frameEffect==='cmyk'){data[i]=255-r;data[i+1]=255-g;data[i+2]=255-b;}else{data[i]=Math.min(255,r*1.3+35);data[i+1]=Math.min(255,g*.8);data[i+2]=Math.min(255,b*1.4+25);}}context.putImageData(image,0,0);if(['pixel','retro'].includes(s.frameEffect)){const small=document.createElement('canvas');small.width=Math.max(1,this.fx.width/pixel);small.height=Math.max(1,this.fx.height/pixel);small.getContext('2d').drawImage(this.fx,0,0,small.width,small.height);context.imageSmoothingEnabled=false;context.clearRect(0,0,this.fx.width,this.fx.height);context.drawImage(small,0,0,this.fx.width,this.fx.height);context.imageSmoothingEnabled=true;}}
  invisibleFx(s,bg,seg){if(!bg||!seg?.data){this.invisible=0;return;}const target=s.invisibleAmount??0;this.invisible=target;if(this.invisible<.01)return;const x=this.x,w=this.c.width,h=this.c.height,m=this.mask.getContext('2d');m.clearRect(0,0,w,h);const im=m.createImageData(w,h),sw=seg.width,sh=seg.height;for(let y=0;y<h;y++)for(let xx=0;xx<w;xx++){const si=Math.floor(y/h*sh)*sw+Math.floor((s.mirror?1-xx/w:xx/w)*sw);if(seg.data[si]>.45)im.data[(y*w+xx)*4+3]=255;}m.putImageData(im,0,0);const rep=this.fx.getContext('2d');rep.clearRect(0,0,w,h);this.video(rep,bg,s);rep.globalCompositeOperation='destination-in';rep.drawImage(this.mask,0,0);rep.globalCompositeOperation='source-over';x.save();x.globalAlpha=this.invisible;x.drawImage(this.fx,0,0);if(s.maskDebug){x.globalAlpha=.35;x.fillStyle='#00ffff';x.globalCompositeOperation='source-atop';x.drawImage(this.mask,0,0);x.globalCompositeOperation='source-over';}x.restore();}
  randomParticle(seg,s,source){const w=this.c.width,h=this.c.height;if(source){const angle=Math.random()*Math.PI*2,speed=.7+Math.random()*1.5;return {x:source.x,y:source.y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed};}for(let n=0;n<10;n++){const x=Math.random()*w,y=Math.random()*h;if(!seg?.data)return {x,y,vx:(Math.random()-.5)*.35,vy:(Math.random()-.5)*.35};const sx=Math.min(seg.width-1,Math.floor((s.mirror?1-x/w:x/w)*seg.width)),sy=Math.min(seg.height-1,Math.floor(y/h*seg.height));if(seg.data[sy*seg.width+sx]>.45)return {x,y,vx:(Math.random()-.5)*.35,vy:(Math.random()-.5)*.35};}return {x:Math.random()*w,y:Math.random()*h,vx:0,vy:0};}
  edgeParticle(){const w=this.c.width,h=this.c.height,edge=Math.floor(Math.random()*4),along=Math.random();return edge===0?{x:along*w,y:0}:edge===1?{x:w,y:along*h}:edge===2?{x:along*w,y:h}:{x:0,y:along*h};}
  dissolve(s,seg,d,t,pose){this.particleRespawns||={count:0,rate:0,since:0};const w=this.c.width,h=this.c.height,count=Math.min(s.particles||600,s.adaptiveParticleLimit||Infinity),dt=Math.min(2,(t-(this.lastParticleTime||t))/16.67);this.lastParticleTime=t;while(this.particles.length<count)this.particles.push(this.randomParticle(seg,s));this.particles.length=count;const hands=d.hands.map(hand=>({...hand,screen:this.point(hand.center,s)})),layer=this.particleLayer.getContext('2d');const source=s.flowSource||'auto',useHand=source==='hand'||(source==='auto'&&hands.length),useBody=source==='body'||(source==='auto'&&!hands.length);if(s.particleMode==='hand'&&useHand){const result=stepHandFlowParticles(this.particles,hands,s,{width:w,height:h},{dt,cursor:this.particleCursor});this.particleCursor=result.cursor;this.particleRespawns.count+=result.respawns;if(!this.particleRespawns.since)this.particleRespawns.since=t;if(t-this.particleRespawns.since>=1000){this.particleRespawns.rate=Math.round(this.particleRespawns.count*1000/(t-this.particleRespawns.since));this.particleRespawns.count=0;this.particleRespawns.since=t;}}else if(s.particleMode==='hand'&&useBody)this.windVector=stepBodyWindParticles(this.particles,pose,this.bodyWind={...s,...this.bodyWind},{width:w,height:h},t,dt);else for(const p of this.particles){p.x+=p.vx*dt*(s.speed||1);p.y+=p.vy*dt*(s.speed||1);if(p.x<0)p.x=w;if(p.x>w)p.x=0;if(p.y<0)p.y=h;if(p.y>h)p.y=0;}layer.save();layer.globalCompositeOperation='source-over';layer.fillStyle=`rgba(0,0,0,${Math.max(.04,1-(s.particleTrail||55)/105)})`;layer.fillRect(0,0,w,h);layer.globalCompositeOperation='lighter';layer.fillStyle=s.particleColor||'#35f4ff';for(const p of this.particles){if(p.shapeMode!==(s.particleShape||'circle')){p.shapeMode=s.particleShape||'circle';p.shape=p.shapeMode==='mixed'?['square','circle','star'][Math.floor(Math.random()*3)]:p.shapeMode;}this.drawParticle(layer,p,s.particleSize||3);}layer.restore();this.x.save();this.x.globalCompositeOperation='screen';this.x.drawImage(this.particleLayer,0,0);this.x.restore();}
  drawParticle(context,particle,size){if(particle.shape==='square'){context.fillRect(particle.x-size/2,particle.y-size/2,size,size);return;}context.beginPath();if(particle.shape==='star'){for(let i=0;i<10;i++){const radius=i%2?size*.23:size*.52,angle=-Math.PI/2+i*Math.PI/5,x=particle.x+Math.cos(angle)*radius,y=particle.y+Math.sin(angle)*radius;i?context.lineTo(x,y):context.moveTo(x,y);}context.closePath();}else context.arc(particle.x,particle.y,size/2,0,Math.PI*2);context.fill();}
  lockPhotoFrame(faces=[],pose=null,data=null){if(!this.stableQuad)return false;const snapshot=document.createElement('canvas');snapshot.width=this.c.width;snapshot.height=this.c.height;snapshot.getContext('2d').drawImage(this.c,0,0);const quad=this.stableQuad.map(p=>({...p})),center={x:quad.reduce((a,p)=>a+p.x,0)/4,y:quad.reduce((a,p)=>a+p.y,0)/4},faceMatch=faces.reduce((best,f,index)=>{const p=this.point(f,{mirror:false}),distance=Math.hypot(p.x-center.x,p.y-center.y);return !best||distance<best.distance?{face:f,index,distance}:best;},null),face=faceMatch?.face,anchor=face?{type:'face',index:faceMatch.index,x:face.x,y:face.y,angle:face.angle||0}:pose?.detected?{type:'pose',x:(pose.shoulder.x+pose.hip.x)/2,y:(pose.shoulder.y+pose.hip.y)/2,angle:pose.angle||0}:data?.hands?.[0]?{type:'hand',x:data.hands[0].center.x,y:data.hands[0].center.y,angle:0}:null;this.photoFrame={snapshot,quad,center,anchor,alpha:1,state:'PHOTO LOCKED'};return true;}
  releasePhotoFrame(){if(this.photoFrame)this.photoFrame.state='FADING';}
  drawPhotoFrame(faces,pose,data,s,t){const photo=this.photoFrame;if(!photo)return;let dx=0,dy=0,rotation=0;if(photo.anchor?.type==='face'&&faces[photo.anchor.index]){const current=faces[photo.anchor.index];dx=(current.x-photo.anchor.x)*(s.mirror?-1:1)*this.c.width;dy=(current.y-photo.anchor.y)*this.c.height;if(s.followRotation)rotation=(current.angle||0)-photo.anchor.angle;}else if(photo.anchor?.type==='pose'&&pose?.detected){const x=(pose.shoulder.x+pose.hip.x)/2,y=(pose.shoulder.y+pose.hip.y)/2;dx=(x-photo.anchor.x)*(s.mirror?-1:1)*this.c.width;dy=(y-photo.anchor.y)*this.c.height;if(s.followRotation)rotation=(pose.angle||0)-photo.anchor.angle;}else if(photo.anchor?.type==='hand'&&data.hands[0]){dx=(data.hands[0].center.x-photo.anchor.x)*(s.mirror?-1:1)*this.c.width;dy=(data.hands[0].center.y-photo.anchor.y)*this.c.height;}this.x.save();this.x.globalAlpha=photo.alpha;this.x.translate(photo.center.x+dx,photo.center.y+dy);this.x.rotate(rotation);this.x.translate(-photo.center.x,-photo.center.y);this.path(photo.quad);this.x.clip();this.x.drawImage(photo.snapshot,0,0);this.x.restore();if(photo.state==='FADING'){photo.alpha-=.05;if(photo.alpha<=0)this.photoFrame=null;}}
  facesInsideFrame(faces,s,quad=this.stableQuad){if(!quad)return [];const bounds={left:Math.min(...quad.map(p=>p.x)),right:Math.max(...quad.map(p=>p.x)),top:Math.min(...quad.map(p=>p.y)),bottom:Math.max(...quad.map(p=>p.y))};return faces.map(face=>{const screen=this.point(face,s),size=face.size*this.c.width*(s.emojiSize||1.25),radius=size/2;return {...face,screen,drawSize:size,intersects:screen.x+radius>=bounds.left&&screen.x-radius<=bounds.right&&screen.y+radius>=bounds.top&&screen.y-radius<=bounds.bottom};}).filter(face=>face.intersects&&circleIntersectsPolygon(face.screen,face.drawSize/2,quad));}
  drawFaceEmojis(faces,s,t){const quad=t-this.quadSeen<350?this.stableQuad:null;if(!quad)return 0;const inside=this.facesInsideFrame(faces,s,quad);this.x.save();this.path(quad);this.x.clip();for(const face of inside){const size=face.drawSize;this.x.save();this.x.translate(face.screen.x,face.screen.y);this.x.rotate((s.mirror?-1:1)*face.angle);this.emoji.draw(this.x,face.expression,0,0,size);this.x.restore();}this.x.restore();return inside.length;}
  debug(d,s,seg,faces,pose){const x=this.ox;x.clearRect(0,0,this.o.width,this.o.height);if(s.debug){x.strokeStyle='#62ffe4';x.fillStyle='#fff';x.lineWidth=2;d.hands.forEach(hand=>{d.bones.forEach(([a,b])=>{x.beginPath();const p=this.point(hand.p[a],s),q=this.point(hand.p[b],s);x.moveTo(p.x,p.y);x.lineTo(q.x,q.y);x.stroke();});hand.p.forEach((p,i)=>{const q=this.point(p,s);x.fillRect(q.x-2,q.y-2,5,5);x.fillText(i,q.x+4,q.y-4);});});}if(s.handFlowDebug&&s.mode==='dissolve'){x.save();x.font='14px monospace';x.fillStyle='#fff';x.fillText(`HANDS ${d.hands.length} · POSE ${pose?.detected?'YES':'NO'} · PARTICLES ${this.particles.length} · RESPAWN/s ${this.particleRespawns.rate} · SEGMENTATION ${seg?.data?'READY':'NOT REQUIRED'} · CANVAS ${this.c.width}×${this.c.height}`,12,22);if(pose?.detected){const shoulder=this.point(pose.shoulder,s),hip=this.point(pose.hip,s);x.strokeStyle='#ffe45c';x.beginPath();x.moveTo(hip.x,hip.y);x.lineTo(shoulder.x,shoulder.y);x.stroke();x.fillText(`BODY ${(pose.angle*180/Math.PI).toFixed(1)}° WIND ${(this.windVector?.x||0).toFixed(2)},${(this.windVector?.y||0).toFixed(2)}`,shoulder.x+8,shoulder.y);}d.hands.forEach(hand=>{const p=this.point(hand.center,s),out=hand.gesture==='OPEN';x.strokeStyle=out?'#35f4ff':'#ff4baf';x.fillStyle=x.strokeStyle;x.beginPath();x.arc(p.x,p.y,12,0,Math.PI*2);x.stroke();x.fillText(`${hand.label} ${hand.gesture} (${Math.round(p.x)},${Math.round(p.y)}) ${out?'SOURCE':'SINK'}`,p.x+16,p.y-8);x.beginPath();x.moveTo(p.x+(out?0:42),p.y);x.lineTo(p.x+(out?42:0),p.y);x.stroke();});for(let i=0;i<Math.min(12,this.particles.length);i++){const particle=this.particles[i];x.strokeStyle='#fff8';x.beginPath();x.moveTo(particle.x,particle.y);x.lineTo(particle.x+particle.vx*8,particle.y+particle.vy*8);x.stroke();}x.restore();}if(s.invisibleDebug&&s.mode==='invisible'){const info=s.invisibleDebugData||{};x.save();x.fillStyle='rgba(0,0,0,.75)';x.fillRect(8,8,390,92);x.fillStyle='#fff';x.font='13px monospace';x.fillText(`GESTURE ${s.invisibleGesture||'UNKNOWN'} · STATE ${s.invisibleState||'VISIBLE'}`,16,28);x.fillText(`CENTER ${info.center?`${info.center.x.toFixed(2)},${info.center.y.toFixed(2)}`:'—'} · VX ${(info.velocity||0).toFixed(2)}`,16,49);x.fillText(`AMPLITUDE ${(info.amplitude||0).toFixed(2)} · REVERSALS ${info.reversals||0} · SALUTE: TEMPLE REGION`,16,70);x.restore();}if(s.expressionDebug&&s.mode==='anime'){const inside=this.facesInsideFrame(faces,s,(performance.now()-this.quadSeen<350)?this.stableQuad:null);x.save();x.fillStyle='rgba(0,0,0,.75)';x.fillRect(8,8,390,100);x.fillStyle='#fff';x.font='13px monospace';x.fillText(`FACE ${faces.length} · FRAME ${this.stableQuad?'TRACKED':'NONE'} · INSIDE ${inside.length}`,16,28);x.fillText(`EXPRESSION: ${inside.map(f=>f.expression).join(' / ')||'—'} (visual estimate)`,16,49);if(inside[0])x.fillText(Object.entries(inside[0].scores||{}).map(([k,v])=>`${k}:${v.toFixed(2)}`).join(' '),16,70);x.restore();}}
}
