export class FXRenderer {
  constructor(canvas,overlay){this.c=canvas;this.x=canvas.getContext('2d',{alpha:false});this.o=overlay;this.ox=overlay.getContext('2d');this.particles=[];}
  resize(w,h){this.c.width=this.o.width=w;this.c.height=this.o.height=h;}
  capture(v){const c=document.createElement('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);return c;}
  reset(){this.particles=[];}
  render(v,d,s,bg,t){const w=this.c.width,h=this.c.height;if(!w)return;const x=this.x;x.save();if(s.mirror){x.translate(w,0);x.scale(-1,1);}x.drawImage(v,0,0,w,h);x.restore(); if(s.mode==='frame'||s.mode==='twist'||s.mode==='anime')this.frame(d,s);if(['invisible','glass','chrome','dissolve'].includes(s.mode))this.transform(d,s,bg,t);if(s.mode==='volume')this.volume(d,s);if(s.mode==='cube')this.cubes(d,s,t);this.debug(d,s);}
  quad(d){if(d.hands.length<2)return null;const a=d.hands[0].p,b=d.hands[1].p;return [a[4],a[8],b[8],b[4]].map(p=>({x:(1-p.x)*this.c.width,y:p.y*this.c.height}));}
  frame(d,s){const q=this.quad(d);if(!q)return;const x=this.x,w=this.c.width,h=this.c.height;x.save();x.beginPath();q.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.closePath();x.clip();if(s.mode==='anime'||s.frameEffect==='pop'){x.globalCompositeOperation='screen';x.fillStyle='rgba(255,30,135,.35)';x.fillRect(0,0,w,h);x.globalCompositeOperation='multiply';x.fillStyle='rgba(0,230,255,.22)';x.fillRect(0,0,w,h);}if(s.frameEffect==='invert'){x.globalCompositeOperation='difference';x.fillStyle='white';x.fillRect(0,0,w,h);}if(s.frameEffect==='pixel'){x.imageSmoothingEnabled=false;const im=x.getImageData(0,0,w,h);for(let y=0;y<h;y+=10)for(let z=0;z<w;z+=10){let i=(y*w+z)*4;for(let yy=0;yy<10;yy++)for(let xx=0;xx<10;xx++){let j=((y+yy)*w+z+xx)*4;im.data[j]=im.data[i];im.data[j+1]=im.data[i+1];im.data[j+2]=im.data[i+2];}}x.putImageData(im,0,0);}x.restore();x.beginPath();q.forEach((p,i)=>i?x.lineTo(p.x,p.y):x.moveTo(p.x,p.y));x.closePath();x.strokeStyle='#4cfbff';x.lineWidth=3;x.shadowBlur=16;x.shadowColor='#4cfbff';x.stroke();x.shadowBlur=0;}
  transform(d,s,bg,t){if(d.gesture!=='FIST')return;const x=this.x,w=this.c.width,h=this.c.height;if(s.mode==='invisible'&&bg)x.drawImage(bg,0,0,w,h);if(s.mode==='glass'){x.globalAlpha=.5;x.filter='blur(7px) saturate(1.7)';x.drawImage(this.c,8,0,w,h);x.filter='none';x.globalAlpha=1;}if(s.mode==='chrome'){x.globalCompositeOperation='overlay';const g=x.createLinearGradient(0,0,w,h);g.addColorStop(0,'#ffffff');g.addColorStop(.4,'#0a1830');g.addColorStop(.7,'#fff');g.addColorStop(1,'#26364b');x.fillStyle=g;x.globalAlpha=s.strength;x.fillRect(0,0,w,h);x.globalAlpha=1;x.globalCompositeOperation='source-over';}if(s.mode==='dissolve'){for(let i=0;i<20;i++)this.particles.push({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*6,vy:-Math.random()*5});}x.fillStyle='#ff4baf';this.particles=this.particles.slice(-s.particles);this.particles.forEach(p=>{p.x+=p.vx*s.speed;p.y+=p.vy*s.speed;x.fillRect(p.x,p.y,2+s.size,2+s.size);});}
  cubes(d,s,t){const x=this.x;d.hands.forEach(hand=>{[8,12,16,20].forEach(i=>{const p=hand.p[i],z=(10+s.size*10+hand.speed*30);const px=(1-p.x)*this.c.width,py=p.y*this.c.height;x.save();x.translate(px,py);x.rotate(t*.001*s.speed);x.fillStyle='#c45bff';x.shadowColor='#46f6ff';x.shadowBlur=18;x.fillRect(-z/2,-z/2,z,z);x.strokeStyle='white';x.strokeRect(-z/2,-z/2,z,z);x.restore();});});}
  volume(d,s){if(!d.hands.length)return;const p=d.hands[0].p[8],x=this.x,px=(1-p.x)*this.c.width,py=p.y*this.c.height,z=90*s.size;x.save();x.translate(px,py);x.strokeStyle='#80faff';x.lineWidth=3;for(let i=0;i<2;i++){x.strokeRect(-z/2+i*20,-z/2-i*20,z,z);}x.beginPath();[-1,1].forEach(a=>[-1,1].forEach(b=>{x.moveTo(a*z/2,b*z/2);x.lineTo(a*z/2+20,b*z/2-20);}));x.stroke();x.restore();}
  debug(d,s){const x=this.ox;x.clearRect(0,0,this.o.width,this.o.height);if(!s.debug)return;x.strokeStyle='#62ffe4';x.fillStyle='#fff';x.lineWidth=2;d.hands.forEach(hand=>{d.bones.forEach(([a,b])=>{x.beginPath();x.moveTo((1-hand.p[a].x)*this.o.width,hand.p[a].y*this.o.height);x.lineTo((1-hand.p[b].x)*this.o.width,hand.p[b].y*this.o.height);x.stroke();});hand.p.forEach((p,i)=>{const px=(1-p.x)*this.o.width,py=p.y*this.o.height;x.fillRect(px-2,py-2,5,5);x.fillText(i,px+4,py-4);});});}
}
