import { ImageSegmenter } from '@mediapipe/tasks-vision';
import { getVisionFileset } from './vision.js';
const model='https://storage.googleapis.com/mediapipe-models/selfie_segmenter/landscape/float16/latest/selfie_segmenter_landscape.tflite';
export class PersonSegmenter {
  constructor({resolveVision=getVisionFileset,createSegmenter=(vision,options)=>ImageSegmenter.createFromOptions(vision,options)}={}){this.resolveVision=resolveVision;this.createSegmenter=createSegmenter;this.segmenter=null;this.loading=null;this.last=null;this.error='';this.failed=false;this.delegate='';this.detecting=false;}
  async init(){if(this.segmenter)return this.segmenter;if(this.loading)return this.loading;if(this.failed)throw new Error(this.error||'Image Segmenter initialization previously failed');this.loading=(async()=>{const vision=await this.resolveVision();let cpuError;
    // The hand tracker already owns the GPU path. Prefer CPU here to avoid a second
    // GPU task/WebGL context; retain GPU as a compatibility fallback.
    for(const delegate of ['CPU','GPU']){try{const instance=await this.createSegmenter(vision,{baseOptions:{modelAssetPath:model,delegate},runningMode:'VIDEO',outputCategoryMask:true,outputConfidenceMasks:false});this.delegate=delegate;return instance;}catch(error){if(delegate==='CPU')cpuError=error;else throw new Error(`Person Segmenter initialization failed. CPU: ${cpuError?.message||'unknown'} / GPU: ${error.message}`);}}
  })().then(x=>{this.segmenter=x;return x;}).catch(e=>{this.error=e.message;this.failed=true;throw e;}).finally(()=>{this.loading=null;});return this.loading;}
  async detect(video,timestamp){if(!this.segmenter||video.readyState<2||this.detecting)return this.last;this.detecting=true;try{const result=this.segmenter.segmentForVideo(video,timestamp);const mask=result.categoryMask;if(mask)this.last={data:mask.getAsFloat32Array(),width:mask.width,height:mask.height,method:'AI'};result.close?.();return this.last;}catch(error){this.error=error.message;this.failed=true;this.close(false);throw error;}finally{this.detecting=false;}}
  close(clearFailure=true){this.segmenter?.close?.();this.segmenter=null;this.last=null;if(clearFailure){this.failed=false;this.error='';}this.delegate='';}
}
export function backgroundDifference(background,video,sensitivity=.18){if(!background||video.readyState<2)return null;const w=320,h=180,a=document.createElement('canvas'),b=document.createElement('canvas');a.width=b.width=w;a.height=b.height=h;const ac=a.getContext('2d',{willReadFrequently:true}),bc=b.getContext('2d',{willReadFrequently:true});ac.drawImage(background,0,0,w,h);bc.drawImage(video,0,0,w,h);const bg=ac.getImageData(0,0,w,h).data,now=bc.getImageData(0,0,w,h).data,out=new Float32Array(w*h),threshold=Math.max(12,Math.min(100,sensitivity*255));for(let i=0,p=0;i<now.length;i+=4,p++){const d=Math.abs(now[i]-bg[i])+Math.abs(now[i+1]-bg[i+1])+Math.abs(now[i+2]-bg[i+2]);out[p]=d>threshold*3?1:0;}return {data:out,width:w,height:h,method:'BACKGROUND DIFFERENCE'};}
